### ISSUE TITLE
Put pagination links elsewhere

### ISSUE THREAD

**Issue by rctneil** [billerickson/Display-Posts-Pagination#13]
Hi @billerickson 

How can I put the pagination links somewhere else in my markup rather than as the last item?

Thanks,
Neil

**Comment by billerickson** [comment]
You could [modify this line](https://github.com/billerickson/Display-Posts-Pagination/blob/master/display-posts-pagination.php#L62) to output the links on a different filter.

I don't plan to push out any updates for this plugin since it's feature complete, but if you do make edits to the plugin files I recommend also [changing the version number to 99](https://github.com/billerickson/Display-Posts-Pagination/blob/master/display-posts-pagination.php#L6) so that if an update does come out in the future, it doesn't overwrite your version (your version will always have a higher version number than the public one).

**Comment by rctneil** [comment]
@billerickson I apologise but i'm getting a bit confused here.

I've managed to stop the pagination links from getting output but not sure how to output them in the place I need.

I have a div like so:

                        <div class="properties-list-navigation">
                            
                        </div>

Please could you help me out a little further here?

Appreciate your time,
Neil

**Comment by billerickson** [comment]
Actually, as I read through the code I don't think it's possible to output the pagination elsewhere. The pagination depends on the shortcode's attributes and query, so can only be output within the shortcode itself.

You could modify the markup of the pagination links to wrap them in `<div class="properties-list-navigation">` [here](https://github.com/billerickson/Display-Posts-Pagination/blob/master/display-posts-pagination.php#L49-L52), but you can't output the pagination links outside the shortcode.
